# Task 3

In [3]:
import task_3_utils as utils

In [14]:
import numpy as np

### Esercizio 1

*Scrivi una funzione che prende in input una matrice e restituisce il massimo.*

In [ ]:
L = np.array([[4, 2, 1, 5], [6, 2, 7, 8], [9, 3, 4, 6], [2, 5, 8, 7]])
massimo = utils.fun_esercizio_1(L)
print(massimo)

9


### Esercizio 2

*Scrivi una funzione che prende in input una matrice quadrata e restituisce True se è simmetrica, False altrimenti*

In [ ]:

matrice_quadrata = [[2, 5, -1], [-8, 3, 4]]
print(utils.fun_esercizio_2(matrice_quadrata))

False


### Esercizio 3

*Scrivi una funzione che prende in input due matrice della stessa dimensione e restituisce la somma dele due matrici elemento per elemento.*

In [26]:
a = np.array ([[4, 3, 6], [1, 6, 9], [8, 2, 5]])
b = np.array ([[1, 4, 5], [2, 8, 3], [7, 9, 6]])
print(utils.fun_esercizio_3(a, b))

[[ 5  7 11]
 [ 3 14 12]
 [15 11 11]]


### Esercizio 4

*Scrivi una funzione che prende in input una matrice e restituisce la matrice normalizzata per righe*

In [24]:
L = np.array([[4, 1, 9], [6, 8, 3], [2, 5, 7]])
print(utils.fun_esercizio_4(L))

[[0.28571429 0.07142857 0.64285714]
 [0.35294118 0.47058824 0.17647059]
 [0.14285714 0.35714286 0.5       ]]


### Esercizio 5

*Scrivi una funzione che prende in input una matrice quadrata e restituisce la somma degli elementi lungo la diagonale principale.*

In [22]:
L = [[3, 2, 7], [8, 2, 1], [5, 8, 4]]
print(utils.fun_esercizio_5(L))

9.0
